import React from 'react';

const ChatGPTSuggestions: React.FC = () => {
  return (
    <div className="chatgpt-suggestions">
      <h2>Home Workout Must Haves!</h2>
      <p>Generated by ChatGPT</p>
    </div>
  );
};

export default ChatGPTSuggestions;