import React, { useEffect, useState } from 'react';

const ChatGPTSuggestions: React.FC = () => {
  const [suggestions, setSuggestions] = useState<string>('');

  useEffect(() => {
    const fetchSuggestions = async () => {
      try {
        const response = await fetch('/api/chatgpt-suggestions');
        const data = await response.json();
        setSuggestions(data.suggestions);
      } catch (error) {
        console.error('Error fetching suggestions:', error);
      }
    };

    fetchSuggestions();
  }, []);

  return (
    <div className="chatgpt-suggestions">
      <h2>Home Workout Must Haves!</h2>
      <p>Generated by ChatGPT</p>
      <div>{suggestions}</div>
    </div>
  );
};

export default ChatGPTSuggestions;